#!/bin/bash

# 쉘의 종류
# sh: linux 초반(1970년대) 많이 사용하던 쉘
# bash: sh의 개선버전 - ubuntu의 기본 쉘

# step 1. 쉘 프로그래밍 기본

echo hello

# 다음 문장은 sh로는 실행되지 않지만 bash에서는 실행 가능
declare -i num=10


# 주석

#1. 단일 주석

: '
2. 멀티라인 주석 1
'

# here document를 사용한 주석
#less <<LABEL    less에 입력으로 전달
<<LABEL          빈 프로그램에 입력으로 전달 -> 주석 효과
2. 멀티라인 주석 2 : LABEL 블록을 표준입력으로 사용
LABEL


