#!/bin/bash

# 반복문 3. until

count=1
until (( "$count" > 20 ))
do
	echo $count
	count=$(($count+1))
done


# 관리자가 로그인 할 때 까지 특정 작업을 수행하는 방법

name="root"
#until [[ $(who | grep $name) != "" ]]
until $( who | grep $name >> /dev/null )
do
	sleep 1
	echo "wait " $name
done

echo $name " is logon"

