#!/bin/bash

# Step 12. 함수 만들기

function foo
{
	echo "fucntion foo"
}

goo()
{
	echo "function goo"
}

function hoo()
{
	echo -n "function hoo called with "
	echo $1, $2

	sum=$(($1+$2))
	#echo $sum
	return $sum
}

# 함수 사용하기
foo
goo
hoo 1 2
echo $?		# 함수 결과 출력


# . sh12 -> 메모리에 함수 로드하기!!!
# 메모리에 함수 로드하기: . 스크립트
# 메모리에서 함수 언로드: unset -f 함수이름

#----------------------------------------------
# 과제 2. 구구단을 출력하는 쉘 함수를 만드세요
# 과제 3. vib 라는 쉘 스크립트 파일을 만드세요
#         vib

