#!/bin/bash

# Step 5. 명령어 실행 결과 확인 및 조사

./sh4
echo $?		# 명령어 (실행파일)의 결과 확인

echo --------------------

grep xxx /etc/passwd
echo $?
grep shim84 /etc/passwd
echo $?		# grep의 실행 결과 - 0: 찾음, 1: 찾지 못함

echo --------------------

# 변수값 조사
name="aaa"

# test 사용
test $name != bbb	# 같지 않다
echo $?				# 결과: 0
test $name = bbb	# '=' 가 하나임에 주의!
echo $?

# 대괄호 [ 조건식 ] 사용
[ $name = bbb ]		# 위 test와 동일
echo $?
[[ $name == bbb ]]	# bash 확장 문법 ('==' 기호로 equal 사용)
echo $?


echo --------------------
# 크기 비교
x=5
y=20

[ $x -gt $y ]		# -gt, -lt, ...
echo $?

(( $x > $y ))		# bash 확장 문법
echo $?


#echo --------------------
# 정리
# 리턴값 조사: $?
# 상등 비교: test $변수=값, [ $변수 = 값 ], [[ $변수 == 값 ]]
# 크기 비교: [ $변수1 -gt $변수2 ], (( $변수1 > $변수2 ))
#echo --------------------


echo --------------------

# [] 를 사용한 파일 조사 - 385p

[ -f "sh1" ]
echo $?


