#!/bin/bash

# Step9. 반복문

# for
: '
for n in 1 3 5 7 9 2 4 6 8 10
do
	echo $n
#done					# do의 종료는 done
#done > a.txt			# redirection
done | sort -n | less	# sort의 -n: 숫자 기준 정렬
'

# 확장 문자와 for
: '
for file in *
do
	echo $file
done
'

# 다른 터미널에서 sleep 10000 & 를 5번 실행하세요.
# 현재 실행중인 모든 sleep 프로세스를 죽여보세요
for pid in $(ps -ef | grep sleep | grep grep -v | awk -F ' ' '{print $2}')
do
	echo kill $pid
	kill $pid
done

