#!/bin/bash

# grep_test2
# 확장 정규 표현식 ERE (Extended Regular Expression)
# : | () {} ? + *

# |: zip or ers (NOT [zipers]: 문자 단위 or)
#grep -h zip|ers grep*.txt		# ERROR: |를 shell의 pipeline으로 해석
#grep -h 'zip|ers' grep*.txt	# ERROR: 동작 안 함
#grep -h -E 'zip|ers' grep*.txt	# OK: -E 옵션 (extended)
#egrep -h 'zip|ers' grep*.txt	# grep -E = egrep

# 문장의 앞 단어가 bz, gz, zip 중 하나로 시작하는 문자열을 찾아라
#egrep -h '^bz|gz|zip' grep*.txt	# FAIL: bz만 시작 조건임
#egrep -h '^bz|^gz|^zip' grep*.txt
#egrep -h '^(bz|gz|zip)' grep*.txt	# OK


# 전화번호 찾기
#egrep -h '[0-9]' phone.txt		# 숫자가 한 개 이상인 것 찾기
#egrep -h '[0-9]-' phone.txt		# 숫자 한 개 이상과 -
#egrep -h '[0-9]-?' phone.txt	# ?: 앞의 문자가 있어도 되고 없어도 된다
#egrep -h '\-[0-9]' phone.txt	# - 와 숫자로 된 것
								# - 가 앞에 있으면 옵션으로 간주, escape 시켜야 함

#egrep -h '\-[0-9]?' phone.txt	# ?: 앞의 문자가 한 번 있거나 없어도 된다
#egrep -h '\-[0-9]*' phone.txt	# *: 앞의 문자가 없거나 여러번 있거나
#egrep -h '\-[0-9]+' phone.txt	# +: 앞의 문자가 한 개 있거나 여러개 있거나
#egrep -h '\-[0-9]$' phone.txt	# $: 앞의 문자로 끝나는 것

# 본격적으로 찾아보자 (xxxx-xxxx)
#egrep -h '^[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]$' phone.txt
# -는 있거나 없거나 (? 도입)
#egrep -h '^[0-9][0-9][0-9][0-9]-?[0-9][0-9][0-9][0-9]$' phone.txt
# - 대신 공백
#egrep -h '^[0-9][0-9][0-9][0-9] [0-9][0-9][0-9][0-9]$' phone.txt
# 공백은 없거나 여러번 있거나 (*)
#egrep -h '^[0-9][0-9][0-9][0-9] *[0-9][0-9][0-9][0-9]$' phone.txt
# 공백 또는 - (| 도입)
#egrep -h '^[0-9][0-9][0-9][0-9](-?| *)[0-9][0-9][0-9][0-9]$' phone.txt
# {}를 사용해 반복횟수 지정
#egrep -h '^[0-9]{3,4}(-?| *)[0-9]{4}$' phone.txt


# 이메일을 찾아라
#egrep '.+@.+\..+' phone.txt


# 전화번호 찾기를 참고해서 핸드폰 번호 찾기 해보세요.
# 잘 되시면 ()도 도전해 보세요. 
egrep '^(\( *(010|011|017|019) *\)|[0-9]{3})( *|( *\- *))[0-9]{3,4}( *|( *\- *))[0-9]{4}' phone.txt


