#!/bin/bash

#1. 환경 변수 개념

AAA="hello"	# 기본 변수는 문자열로 취급
echo AAA	# "AAA" 출력
echo $AAA	# AAA 변수의 내용 출력


#2. 미리 정의된 환경변수가 있다.

echo $PATH


#3. 모든 환경 변수 출력
#set		# 환경 변수와 함수 같이 출력
#env		# 환경 변수만 출력


echo 4. prompt를 관리하는 환경 변수 - 155p
echo $PS1





