#!/bin/bash

# 파일 압축 관리. 18장 227p

#0. test 디렉토리와 파일 만들기
#mkdir -p SOURCE/dir-{00{1..9},0{10..99},100}	# 잘 생각해 보세요: 100개 디렉토리 생성

#touch aaa	# aaa 파일의 최종 접근 날짜가 현재로 변경... 파일이 없으면 생성
#touch SOURCE/dir-{00{1..9},0{10..99},100}/file-{A..Z}	# 2600개 파일 생성


#1. 파일을 묶기 - 232p 표 참고
#tar cf SOURCE.tar SOURCE	# c는 아카이브 생성..


#2. 아카이브 해제
#mkdir TEST
#cd TEST
#tar xf ../SOURCE.tar		# 실행하면 TEST/SOURCE가 생깁니다.


#3. 압축하기 - 228p
#gzip SOURCE.tar			# 압축 (=> SOURCE.tar.gz)
#gunzip SOURCE.tar.gz		# 압축 해제 (=> SOURCE.tar)


#4. 압축하기 2 - 230p
#bzip2 SOURCE.tar			# 압축 (=> SOURCE.tar.bz2)
#bunzip2 SOURCE.tar.bz2		# 압축 해제 (=> SOURCE.tar)


#5. 압축과 tar를 한 번에 푸는 방법
#rm -r TEST
#mkdir TEST
#cd TEST

#tar xjf ../SOURCE.tar.bz2	# xf: tar만 풀기
							# xjf: bunzip2 + tar 풀기
							# xzf: gunzip + tar 풀기

# 웹에서 오픈소스 다운 받기
wget http://www.netgull.com/gcc/releases/gcc-6.1.0/gcc-6.1.0.tar.bz2

# GCC_SOURCE라는 폴더를 만들고 그 곳에 GCC 소스를 풀어보세요.
mkdir GCC_SOURCE
cd GCC_SOURCE
tar xjf ../gcc-6.1.0.tar.bz2




